### ISSUE TITLE
TODO: Asynchronous version

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/spotiyt-server#1]
Libraries: [HTTPX](https://github.com/encode/httpx), [FastAPI](https://github.com/tiangolo/fastapi)

- [x] Create a new branch
- [x] Make youtube-search-python asynchronous
- [x] Make SpotifyHandler asynchronous
- [x] Make youtube-dl asynchronous (using subprocesses I guess)
- [x] Make mutagen asynchronous
- [x] Make YoutubeHandler asynchronous
- [x] Replace Flask with FastAPI

**Comment by alexmercerind** [comment]
Hi @raitonoberu !
**I'm really very happy to get your support.**

However, as far as  I recall (my experience), we generally await for other async functions inside an async function. I mean, most of the time, we need a synchronous execution inside an async function...
e.g. **we await a network request, so that we can get the body/json before moving to next statement. So, for the most of the time the execution ends up being synchronous within an async function**. So, I highly doubt if this change would give us any performance benefits (I can be wrong too 😅).

In my asynchronous programming experience... **I mostly use asynchronous programming only when, I want the execution in parallel**, for which I use ```asyncio.gather(...)``` in Python. **But in this back-end (in general), everything is very procedure based**... **We cannot do stuff in parallel** e.g. **We cannot get the metadata in parallel of searching** (as it uses some stuff like track name, artists etc. from metadata itself for searching in YT) or **we cannot get the track metadata in parallel of downloading** (as that gets added to the audio binary using mutagen later on.). So most of the stuff ends up being synchronous.

In the fronted flutter app, however, I'm already using async/await.
**The change to FastAPI seems really promising... I their documentation is nicely written as well.**

IT'S JUST A BIT OF DISCUSS... MOST LIKELY, I'M WRONG.

I'm not that familiar with Python's async/await, but enough familiar JavaScript's Promises and Dart's Futures with async/await knowledge.

Thanks a lot 😃!

**Comment by raitonoberu** [comment]
Hi @alexmercerind!

About the change to FastAPI... I have some interesting tests.
I've created 3 server apps: sync flask, sync fastapi and async fastapi. They all do the same thing: they sleep for 0.5 seconds (emulation of searching, downloading etc.). Then I created a client that sends 10 requests at the same time. Source code:
<details>
Flask app (waitress server):

```python3
# server_flask.py

from flask import Flask
import waitress
from time import sleep

app = Flask(__name__)

@app.route("/")
def main():
    sleep(0.5)  # we emulate Spotify search, downloading etc.
    return "get your song bro"


if __name__ == '__main__':
    waitress.serve(app, port=8000)

```

FastAPI sync app (uvicorn server)

```python3
# server_fastapi_sync.py

from fastapi import FastAPI
import uvicorn
from time import sleep

app = FastAPI()

@app.get("/")
def main():
    sleep(0.5)  # we emulate Spotify search, downloading etc.
    return "get your song bro"


if __name__ == "__main__":
    uvicorn.run(__name__ + ":app", port=8000)

```

FastAPI async app (uvicorn server)

```python3
# server_fastapi_async.py

from fastapi import FastAPI
import uvicorn
from asyncio import sleep

app = FastAPI()

@app.get("/")
async def main():
    await sleep(0.5)  # we emulate Spotify search, downloading etc.
    return "get your song bro"


if __name__ == "__main__":
    uvicorn.run(__name__ + ":app", port=8000)

```
</details>

Test results:
Flask ~1.8 secs
FastAPI sync: ~1.4 secs
FastAPI async: ~0.8 secs

The asynchronous version processes multiple requests simultaneously, while the synchronous version is limited by the number of workers.

**Comment by alexmercerind** [comment]
Hi @raitonoberu !

First of all, you have great knowledge about Python.

That was some really great case study. Thanks a lot for taking your time with it.
Those results with FastAPI async are really really promising.

I never knew asynchronous programming has performance benefits (I thought it only happens with threading). I only went with asynchronous stuff for parallel execution.

**Comment by alexmercerind** [comment]
Hi again @raitonoberu!
I have sent a request to transfer the ownership of this repository to you. You can cultivate and develop this. Don't worry I'll keep making commits.

You can change the name/README of the repository the way you like. You can make the project a bit more informative (you can change project name to something like spotify downloader etc. from harmonoid-service)

It can really help this project grow independently, which I will still use in my app. And I feel that other people will find useful too.

Thanks!

**Comment by raitonoberu** [comment]
Hi @alexmercerind! (a greeting once a day is enough i guess 😁)

Thank you, this will allow you to focus on the frontend and me to focus on the backend. We will do our best!

**Comment by alexmercerind** [comment]
[harmonoid-v0.0.1-pre-release-arm64-v8a-release.apk.zip](https://github.com/raitonoberu/harmonoid-service/files/5129649/harmonoid-v0.0.1-pre-release-arm64-v8a-release.apk.zip)

Hello @raitonoberu again!
Here is your APK.
You can change server and language of the app from the third tab of the app 

But, since I complied it in hurry... It has few bugs:
- On fresh start of app,  you will see no characters on screen (to fix this, close the app and reopen it)
- UI can be bit choppy on newly added screens.

I've made its ZIP because GitHub does not allow APK as attachment.

**Comment by alexmercerind** [comment]
These were my last commits for a while.
I'll return to GitHub in a week now.

Thanks.

I made a Gitter [here](https://gitter.im/harmonoid/community). You can join the chat. (GitHub issue comments are not good place for discussion 😅)

**Comment by alexmercerind** [comment]
Hi!
I just wanted to ask if the server changing is working fine? I tested it and it worked.

The "valid server" is decided if the response of the homepage ("/") of the URL gives response "service is running"...If that string matches then only server is added. 
Our this backend already gives "service is running" in "/" response, thus is a valid server.

I added this just in case people mess with the app in future. I hope it is not causing any problem to you.

**Comment by raitonoberu** [comment]
Hi!
Yeah, thank you!
<details>
<a href="https://ibb.co/8s4W9Ss"><img src="https://i.ibb.co/h91PVt9/MB3-NPmh-Wh-U.jpg" alt="MB3-NPmh-Wh-U" border="0" /></a>

As you can see, HTTP requests are now being sent to my own server.
</details>

**Comment by raitonoberu** [comment]
Ok, I'm almost done with this. Now asynchronous version is deployed on my development server (http://harmonoid-ru.herokuapp.com/). I need to optimize a few things (faster downloading with aria2c & faster json dumping with orjson) before using it as a main server.

**Comparison**:
I wrote a simple test script that simulates downloading all the album tracks.
<details>
<summary>Source code</summary>
If you want to try it, you probably should change album_name string (cuz it is already downloaded)

```python3
import httpx
import asyncio
from time import time


album_name = "Tessa Violet - Halloway"

url_sync = "http://harmonoidservice.herokuapp.com/"
url_async = "http://harmonoid-ru.herokuapp.com/"


async def get(url, endpoint, params, stream=True):
    async with httpx.AsyncClient() as client:
        time0 = time()
        if stream:  # make a request without downloading
            req = client.build_request("GET", url + endpoint, params=params)
            r = await client.send(req, stream=True, timeout=None)
            await r.aclose()
        else:
            r = await client.get(url + endpoint, params=params, timeout=None)
        print(f"{endpoint}: {round(time() - time0, 2)} seconds ({r.status_code})")
        return r


async def main(count):
    print("Getting album " + album_name)

    albums = await get(url_async, "search", {"keyword": album_name, "limit": 1}, False)
    if not albums.json()["albums"]:
        print("Not found")
        return
    album_id = albums.json()["albums"][0]["album_id"]
    tracks = await get(url_async, "albuminfo", {"album_id": album_id}, False)
    tracks = [i["track_id"] for i in tracks.json()["tracks"]]

    print(len(tracks), "tracks")

    print("\nSync:")
    time0 = time()
    tasks = [get(url_sync, "trackdownload", {"track_id": id}) for id in tracks]
    await asyncio.gather(*tasks)
    print(
        f"\nSync /trackdownload ({len(tracks)} requests): {round(time() - time0, 2)} seconds"
    )

    print("\nAsync:")
    time0 = time()
    tasks = [get(url_async, "trackdownload", {"track_id": id}) for id in tracks]
    await asyncio.gather(*tasks)
    print(
        f"\nAsync /trackdownload ({len(tracks)} requests): {round(time() - time0, 2)} seconds"
    )


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(1))

```
</details>

<details>
<summary>Output</summary>

```
Getting album Tessa Violet - Halloway
search: 0.88 seconds (200)
albuminfo: 0.46 seconds (200)
5 tracks

Sync:
trackdownload: 2.57 seconds (200)
trackdownload: 5.73 seconds (200)
trackdownload: 7.7 seconds (200)
trackdownload: 9.71 seconds (200)
trackdownload: 14.81 seconds (200)

Sync /trackdownload (5 requests): 14.93 seconds

Async:
trackdownload: 5.3 seconds (200)
trackdownload: 5.35 seconds (200)
trackdownload: 5.87 seconds (200)
trackdownload: 10.23 seconds (200)
trackdownload: 10.9 seconds (200)

Async /trackdownload (5 requests): 10.96 seconds
```
```
Getting album YUNGBLUD - the underrated youth
search: 1.0 seconds (200)
albuminfo: 0.46 seconds (200)
6 tracks

Sync:
trackdownload: 2.71 seconds (200)
trackdownload: 3.73 seconds (200)
trackdownload: 4.91 seconds (200)
trackdownload: 5.77 seconds (200)
trackdownload: 7.28 seconds (200)
trackdownload: 7.98 seconds (200)

Sync /trackdownload (6 requests): 8.14 seconds

Async:
trackdownload: 3.51 seconds (200)
trackdownload: 3.57 seconds (200)
trackdownload: 3.87 seconds (200)
trackdownload: 3.86 seconds (200)
trackdownload: 4.48 seconds (200)
trackdownload: 4.63 seconds (200)

Async /trackdownload (6 requests): 4.75 seconds
```
```
Getting album Nirvana - Bleach
search: 0.81 seconds (200)
albuminfo: 0.44 seconds (200)
13 tracks

Sync:
trackdownload: 2.31 seconds (200)
trackdownload: 2.72 seconds (200)
trackdownload: 4.15 seconds (200)
trackdownload: 4.12 seconds (200)
trackdownload: 5.62 seconds (200)
trackdownload: 5.69 seconds (200)
trackdownload: 7.7 seconds (200)
trackdownload: 7.67 seconds (200)
trackdownload: 9.08 seconds (200)
trackdownload: 9.46 seconds (200)
trackdownload: 11.29 seconds (200)
trackdownload: 11.09 seconds (200)
trackdownload: 12.83 seconds (200)

Sync /trackdownload (13 requests): 13.12 seconds

Async:
trackdownload: 5.74 seconds (200)
trackdownload: 5.88 seconds (200)
trackdownload: 5.68 seconds (200)
trackdownload: 5.94 seconds (200)
trackdownload: 5.69 seconds (200)
trackdownload: 5.83 seconds (200)
trackdownload: 5.66 seconds (200)
trackdownload: 5.84 seconds (200)
trackdownload: 5.94 seconds (200)
trackdownload: 6.25 seconds (200)
trackdownload: 6.28 seconds (200)
trackdownload: 6.45 seconds (200)
trackdownload: 7.0 seconds (200)

Async /trackdownload (13 requests): 7.14 seconds
```
Note that I have terrible internet speed, so you will probably get better results.
</details>

Take a look at the time when tracks are downloaded asynchronously. It is approximately the same in each request.

We have increased the speed of simultaneous streams by ~30-40% and I'm not gonna stop :)

**Comment by alexmercerind** [comment]
AMAZING WORK!

All I can say is that, thanks a lot for contribution.
I'm really glad that you found this project interesting and I believe you'll love the music experience of it aswell.

You've literally doubled the performance. What are great work...😃😃😃!

Thanks a lot again!

**Comment by alexmercerind** [comment]
After all this great work from you, don't forget to change the name in the LICENSE 😉. 
I also recommend to change the name of this project to something like spotify-downloader etc. (whatever) you like. I'm mentioning you and this repo in the about section of the app.

And replace the Flask in the README with FastAPI. 

All you did is great.
Thanks a lot!

**Comment by raitonoberu** [comment]
Hi @alexmercerind!
I'm really glad to know that you like it :)

I'll fix the README & LICENSE when I'm done with the rest.

**Comment by alexmercerind** [comment]
Hi @mytja !

I just added a new pre-release.

You can download the new APK [here](https://github.com/alexmercerind/harmonoid/releases/download/v0.0.1%2B2/harmonoid-v0.0.1+2-pre-release.apk).

**Changelog:** https://github.com/alexmercerind/harmonoid/releases/tag/v0.0.1%2B2

**I hope this will greatly improve your app experience. It now has many improvements and translations provided by you.**
